[font]
normal = { family = "ZedMono Nerd Font", style = "regular"}
bold = { family = "ZedMono Nerd Font", style = "regular"}
size = 14

[window]
dimensions = { columns = 130, lines = 30 }
padding.x = 10
padding.y = 10


[mouse]
hide_when_typing = true
#bindings = []

[keyboard]
bindings = [
    { key = "F11", action = "ToggleFullscreen" },
]

[general]
import = ["~/.config/alacritty/theme/catppuccin-mocha.toml"]
