import = ["~/.config/alacritty/theme/rose-pine-moon.toml"]

[font]
normal = { family = "M+1Code Nerd Font Mono", style = "regular"}
size = 13.5

[window]
dimensions = { columns = 130, lines = 30 }
padding.x = 10
padding.y = 10
opacity = 1.0
