# Opasity
opacity-rule = [
     "95:class_g = 'Alacritty' && focused",
     "70:class_g = 'Alacritty' && !focused",
     "95:class_g = 'XTerm' && focused",
     "70:class_g = 'XTerm' && !focused",
     "95:class_g = 'Firefox' && focused",
     "70:class_g = 'Firefox' && !focused",
     "95:class_g = 'qutebrowser' && focused",
     "70:class_g = 'qutebrowser' && !focused"
];

blur: {
   method    = "gaussian";
   size      = 20;
   deviation = 4.5;
   kern      = "5x5gaussian";
}

frame-opacity=1;

# GLX backend
backend = "glx";
glx-no-stencil = true;
glx-copy-from-front = false;
use-damage=true;
glx-no-rebind-pixmap = true;
xrender-sync-fence = true;


# Shadows
shadow = true;
shadow-radius = 1;
shadow-offset-x = 1;
shadow-offset-y = 1;
shadow-opacity = 0.3;
shadow-ignore-shaped = false;
