# Opasity
opacity-rule = [
     "90:class_g = 'Alacritty' && focused",
     "80:class_g = 'Alacritty' && !focused",
     "90:class_g = 'kitty' && focused",
     "80:class_g = 'kitty' && !focused",
     "90:class_g = 'XTerm' && focused",
     "80:class_g = 'XTerm' && !focused",
     "90:class_g = 'Firefox' && focused",
     "80:class_g = 'Firefox' && !focused",
     "100:class_g = 'qutebrowser' && focused",
     "80:class_g = 'qutebrowser' && !focused"
];

blur: {
   method    = "box";
   size      = 15;
}

frame-opacity=1;

# GLX backend
backend = "xrender";
glx-no-stencil = true;
glx-copy-from-front = false;
use-damage=true;
glx-no-rebind-pixmap = true;
xrender-sync-fence = true;


# Shadows
shadow = true;
shadow-radius = 1;
shadow-offset-x = 1;
shadow-offset-y = 1;
shadow-opacity = 0.3;
shadow-ignore-shaped = false;
