#!/bin/zsh

if [[ -e ${HOME}/.pyenv ]]; then
    export PYENV_ROOT="${HOME}/.pyenv"
fi

if [[ ! -e "${HOME}/.local/share/fonts" ]]; then
    mkdir -p "${HOME}/.local/share/fonts"
fi

if [[ -e ${XDG_CONFIG_HOME}/emacs/bin ]]; then
    export PATH="${XDG_CONFIG_HOME}/emacs/bin:${PATH}"
fi
