#!/bin/zsh
##########################################################
##                   Prompt                             ##
##########################################################
fpath=($HOME/.local/src/pure $fpath)


##########################################################
##                 Core Settings                        ##
##########################################################
bindkey -e
tabs 4


##########################################################
##                 History Settings                     ##
##########################################################
setopt EXTENDED_HISTORY          # Write the history file in the ':start:elapsed;command' format.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire a duplicate event first when trimming history.
setopt HIST_IGNORE_DUPS          # Do not record an event that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete an old recorded event if a new event is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a previously found event.
setopt HIST_IGNORE_SPACE         # Do not record an event starting with a space.
setopt HIST_SAVE_NO_DUPS         # Do not write a duplicate event to the history file.
setopt HIST_VERIFY               # Do not execute immediately upon history expansion.
export fpath=(${HOME}/.local/share/zsh/site-functions $fpath)


##########################################################
##                      Alias                           ##
##########################################################
alias e="emacs -nw"
alias ls="ls --color=auto"
alias tree="tree -C"


##########################################################
##                      DIRENV                          ##
##########################################################
eval "$(direnv hook zsh)"


##########################################################
##                      ZOXIDE                          ##
##########################################################
eval "$(zoxide init --cmd cd zsh)"


##########################################################
##                        ZFZ                           ##
##########################################################
source <(fzf --zsh)


##########################################################
##                       mise                           ##
##########################################################
eval "$(~/.local/bin/mise activate zsh)"


##########################################################
##                      Completion                      ##
##########################################################
autoload -Uz compinit; compinit
autoload -U promptinit; promptinit
prompt pure
